services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    Dic\UVDesk\IvrsBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Templates,Package}'

    Dic\UVDesk\IvrsBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
        
    Dic\UVDesk\IvrsBundle\API\:
        resource: '../../API/*'
        tags: ['controller.service_arguments']
    
    Dic\UVDesk\IvrsBundle\Providers\ApiCredentials:
        arguments: ['@security.firewall.map']
    
    Dic\UVDesk\IvrsBundle\Security\Guards\IVRSAPIGuard:
        arguments: ['@security.firewall.map']
    
    Dic\UVDesk\IvrsBundle\EventListeners\API\KernelRequest:
        arguments: ['@security.firewall.map']
        tags:
            - { name: kernel.event_listener, event: kernel.request }
            - { name: kernel.event_listener, event: kernel.response }
    
    Dic\UVDesk\IvrsBundle\EventListeners\API\KernelException:
        arguments: ['@security.firewall.map']
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
